name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps: 
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd websearch
          git pull
          docker build -t "websearch" .
          docker run \
            --rm \ 
            --mount source=websearch_index,target=/app/data \
            websearch index --sqlite data/new_index.db
          docker stop  websearch || true
          docker run --rm --mount source=websearch_index,target=/data  busybox mv data/new_index.db data/index.db
          docker run \
            --rm \
            --detach \
            -p 8080:8080 \
            --mount source=websearch_index,target=/app/data \
            websearch server --sqlite data/index.db
            
          
          
